### PR TITLE
Added some styles(colors) to the navbar

### PR DESCRIPTION
**Pull request by real-coder007Ravi**
To make the display pleasing for the end user

### CODE REVIEW

**Comment by suraj-fusion** [comment]
Why are you using two different accounts?

**Comment by real-coder007Ravi** [comment]
I am not able to understand i am making the pull request via my one account when i see on your page it is showing two accounts

**Comment by suraj-fusion** [comment]
I dont know maybe because you are logged in on your pc with a different account on github you are using different account ..........you can first re register on the account from which you are making a pull request which is this one @Ravi-developer246383  and then i will merge

**Comment by real-coder007Ravi** [comment]
Okk thank u i actually wanted to make a pull request using my account real-coder007Ravi and i will do so now

**Comment by real-coder007Ravi** [comment]
Please see  i have created the pull request from my account from which i wanted to create. could you please check and merge.

**Pull request merged**
